#!/bin/sh

# cd .git/hooks && ln -s ../../hooks/pre-commit ./pre-commit && chmod +x ./pre-commit && cd ../../

# $PWD working dir
reactPath=.

$PWD/$reactPath/node_modules/.bin/eslint $reactPath/src --ext .js --fix

exit 0
