export enum Endpoint {
  home = '/',
  last = '/last',
  lastHour = '/last/hour',
  lastDay = '/last/today',
  lastWeek = '/last/week',
  lastMonth = '/last/month',
  top = '/top',
  topToday = '/top/today',
  topYesterday = '/top/yesterday',
  topHour = '/top/hour',
  topWeek = '/top/week',
  topMonth = '/top/month',
  youtube = '/youtube',
  soundcloud = '/soundcloud',
  bandcamp = '/bandcamp',
}
