name: deploy-ftp--onPublished

on:
  release:
    types:
      - published

jobs:
  deploy-ftp--onPublished:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - run: yarn install --pure-lockfile

      - run: yarn build

      - uses: samkirkland/ftp-deploy-action@master
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: './build/'