name: docker-gpr-build-push-v1--onPublished

on:
  release:
    types:
      - published

jobs:
  docker-gpr-build-push-v1--onPublished:
    runs-on: ubuntu-latest 
    steps:

      - run: echo "IMAGE=$(echo "${{ github.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")" >> $GITHUB_ENV

      - uses: actions/checkout@master

      - uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          repository: ${{ github.repository }}/${{ env.IMAGE }}
          tag_with_ref: true
          tags: latest
