name: push-yarn-lint

on:
  push:
    branches:
      - master

jobs:
  # yarn lint
  yarn-lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: yarn

      - run: yarn lint

      - run: |
          git config --global user.email "asfalte@bamdadsabbagh.com"
          git config --global user.name "asfalte"

      - run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "fix: auto linting"
      
      - run: git push
